# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Use self-hosted runner
    steps:
      - uses: actions/checkout@v3
      - name: Run a script
        run: echo "Hello from the self-hosted runner!"

